stages:
  - linting
  - test
  - build

unit-test:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python3 -m unittest discover

lint:
  stage: linting
  image: python:3.10
  script:
    - pip install flake8
    - flake8

markdownlint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/markdownlint:latest
  script:
    - mdl --style all --warnings .

build-package:
  stage: build
  image: python:3.10
  script:
    - pip install build
    - python -m build
    - pip install dist/myrunner-*-py3-none-any.whl
    - echo "Test package"
    - myrunner unit
  artifacts:
    paths:
      - dist/myrunner-*-py3-none-any.whl
  only:
    - tags
  except:
    - branches
