stages:
  - test
  - build

unit-test:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python3 -m unittest discover

lint:
  stage: test
  image: python:3.10
  script:
    - pip install flake8
    - flake8

build-package:
  stage: build
  image: python:3.10
  script:
    - pip install build
    - python -m build
    - pip install dist/myrunner-0.2.0-py3-none-any.whl
    - echo "Test package"
    - myrunner test
  artifacts:
    paths:
      - dist/myrunner-0.2.0-py3-none-any.whl
